services:
  redis:
    container_name: redis_container_mou
    image: redis:7.4.2-bookworm
  django:
    container_name: django_container_mou
    build: 
      context: . #the directory containing the Dockerfile and all files needed for the build
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/ #Maps the current directory (host) to /usr/src/app/ inside the container. This enables live code updates and easier development.
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on: #redis container/service will start first before django container starts
      - redis



